//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: RoomMessage.proto
namespace msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgType")]
  public partial class MsgType : global::ProtoBuf.IExtensible
  {
    public MsgType() {}
    

    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }

    private msg.MessageType _msgType = msg.MessageType.PlayerEnter;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"msgType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(msg.MessageType.PlayerEnter)]
    public msg.MessageType msgType
    {
      get { return _msgType; }
      set { _msgType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgPlayerEnter")]
  public partial class MsgPlayerEnter : global::ProtoBuf.IExtensible
  {
    public MsgPlayerEnter() {}
    

    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }

    private float _positionX = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"positionX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float positionX
    {
      get { return _positionX; }
      set { _positionX = value; }
    }

    private float _positionY = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"positionY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float positionY
    {
      get { return _positionY; }
      set { _positionY = value; }
    }

    private float _positionZ = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"positionZ", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float positionZ
    {
      get { return _positionZ; }
      set { _positionZ = value; }
    }

    private float _forwardX = default(float);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"forwardX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float forwardX
    {
      get { return _forwardX; }
      set { _forwardX = value; }
    }

    private float _forwardY = default(float);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"forwardY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float forwardY
    {
      get { return _forwardY; }
      set { _forwardY = value; }
    }

    private float _forwardZ = default(float);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"forwardZ", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float forwardZ
    {
      get { return _forwardZ; }
      set { _forwardZ = value; }
    }

    private float _curHealth = default(float);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"curHealth", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float curHealth
    {
      get { return _curHealth; }
      set { _curHealth = value; }
    }

    private float _maxHealth = default(float);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"maxHealth", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float maxHealth
    {
      get { return _maxHealth; }
      set { _maxHealth = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgPlayerMove")]
  public partial class MsgPlayerMove : global::ProtoBuf.IExtensible
  {
    public MsgPlayerMove() {}
    

    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }

    private float _directionX = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"directionX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float directionX
    {
      get { return _directionX; }
      set { _directionX = value; }
    }

    private float _directionY = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"directionY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float directionY
    {
      get { return _directionY; }
      set { _directionY = value; }
    }

    private float _positionX = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"positionX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float positionX
    {
      get { return _positionX; }
      set { _positionX = value; }
    }

    private float _positionY = default(float);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"positionY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float positionY
    {
      get { return _positionY; }
      set { _positionY = value; }
    }

    private float _positionZ = default(float);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"positionZ", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float positionZ
    {
      get { return _positionZ; }
      set { _positionZ = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgPlayerRotate")]
  public partial class MsgPlayerRotate : global::ProtoBuf.IExtensible
  {
    public MsgPlayerRotate() {}
    

    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }

    private float _forwardX = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"forwardX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float forwardX
    {
      get { return _forwardX; }
      set { _forwardX = value; }
    }

    private float _forwardY = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"forwardY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float forwardY
    {
      get { return _forwardY; }
      set { _forwardY = value; }
    }

    private float _forwardZ = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"forwardZ", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float forwardZ
    {
      get { return _forwardZ; }
      set { _forwardZ = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgPlayerStop")]
  public partial class MsgPlayerStop : global::ProtoBuf.IExtensible
  {
    public MsgPlayerStop() {}
    

    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgPlayerShoot")]
  public partial class MsgPlayerShoot : global::ProtoBuf.IExtensible
  {
    public MsgPlayerShoot() {}
    

    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }

    private float _positionX = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"positionX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float positionX
    {
      get { return _positionX; }
      set { _positionX = value; }
    }

    private float _positionY = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"positionY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float positionY
    {
      get { return _positionY; }
      set { _positionY = value; }
    }

    private float _positionZ = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"positionZ", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float positionZ
    {
      get { return _positionZ; }
      set { _positionZ = value; }
    }

    private float _forwardX = default(float);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"forwardX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float forwardX
    {
      get { return _forwardX; }
      set { _forwardX = value; }
    }

    private float _forwardY = default(float);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"forwardY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float forwardY
    {
      get { return _forwardY; }
      set { _forwardY = value; }
    }

    private float _forwardZ = default(float);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"forwardZ", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float forwardZ
    {
      get { return _forwardZ; }
      set { _forwardZ = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgPlayerSetHealth")]
  public partial class MsgPlayerSetHealth : global::ProtoBuf.IExtensible
  {
    public MsgPlayerSetHealth() {}
    

    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }

    private float _curHealth = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"curHealth", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float curHealth
    {
      get { return _curHealth; }
      set { _curHealth = value; }
    }

    private float _maxHealth = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"maxHealth", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float maxHealth
    {
      get { return _maxHealth; }
      set { _maxHealth = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgPlayerExit")]
  public partial class MsgPlayerExit : global::ProtoBuf.IExtensible
  {
    public MsgPlayerExit() {}
    

    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgPlayerDeath")]
  public partial class MsgPlayerDeath : global::ProtoBuf.IExtensible
  {
    public MsgPlayerDeath() {}
    

    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }

    private int _killerID = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"killerID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int killerID
    {
      get { return _killerID; }
      set { _killerID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MessageType")]
    public enum MessageType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerEnter", Value=0)]
      PlayerEnter = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerMove", Value=1)]
      PlayerMove = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerRotate", Value=2)]
      PlayerRotate = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerStop", Value=3)]
      PlayerStop = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerShoot", Value=4)]
      PlayerShoot = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerSetHealth", Value=5)]
      PlayerSetHealth = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerExit", Value=6)]
      PlayerExit = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerDeath", Value=7)]
      PlayerDeath = 7
    }
  
}