// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: RoomMessage.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_PlayerEnter     MessageType = 0
	MessageType_PlayerMove      MessageType = 1
	MessageType_PlayerRotate    MessageType = 2
	MessageType_PlayerStop      MessageType = 3
	MessageType_PlayerShoot     MessageType = 4
	MessageType_PlayerSetHealth MessageType = 5
	MessageType_PlayerExit      MessageType = 6
	MessageType_PlayerDeath     MessageType = 7
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "PlayerEnter",
		1: "PlayerMove",
		2: "PlayerRotate",
		3: "PlayerStop",
		4: "PlayerShoot",
		5: "PlayerSetHealth",
		6: "PlayerExit",
		7: "PlayerDeath",
	}
	MessageType_value = map[string]int32{
		"PlayerEnter":     0,
		"PlayerMove":      1,
		"PlayerRotate":    2,
		"PlayerStop":      3,
		"PlayerShoot":     4,
		"PlayerSetHealth": 5,
		"PlayerExit":      6,
		"PlayerDeath":     7,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_RoomMessage_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_RoomMessage_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_RoomMessage_proto_rawDescGZIP(), []int{0}
}

type MsgType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int32       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MsgType MessageType `protobuf:"varint,2,opt,name=msgType,proto3,enum=msg.MessageType" json:"msgType,omitempty"`
}

func (x *MsgType) Reset() {
	*x = MsgType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RoomMessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgType) ProtoMessage() {}

func (x *MsgType) ProtoReflect() protoreflect.Message {
	mi := &file_RoomMessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgType.ProtoReflect.Descriptor instead.
func (*MsgType) Descriptor() ([]byte, []int) {
	return file_RoomMessage_proto_rawDescGZIP(), []int{0}
}

func (x *MsgType) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MsgType) GetMsgType() MessageType {
	if x != nil {
		return x.MsgType
	}
	return MessageType_PlayerEnter
}

type MsgPlayerEnter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PositionX float32 `protobuf:"fixed32,2,opt,name=positionX,proto3" json:"positionX,omitempty"`
	PositionY float32 `protobuf:"fixed32,3,opt,name=positionY,proto3" json:"positionY,omitempty"`
	PositionZ float32 `protobuf:"fixed32,4,opt,name=positionZ,proto3" json:"positionZ,omitempty"`
	ForwardX  float32 `protobuf:"fixed32,5,opt,name=forwardX,proto3" json:"forwardX,omitempty"`
	ForwardY  float32 `protobuf:"fixed32,6,opt,name=forwardY,proto3" json:"forwardY,omitempty"`
	ForwardZ  float32 `protobuf:"fixed32,7,opt,name=forwardZ,proto3" json:"forwardZ,omitempty"`
	CurHealth float32 `protobuf:"fixed32,8,opt,name=curHealth,proto3" json:"curHealth,omitempty"`
	MaxHealth float32 `protobuf:"fixed32,9,opt,name=maxHealth,proto3" json:"maxHealth,omitempty"`
}

func (x *MsgPlayerEnter) Reset() {
	*x = MsgPlayerEnter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RoomMessage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPlayerEnter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPlayerEnter) ProtoMessage() {}

func (x *MsgPlayerEnter) ProtoReflect() protoreflect.Message {
	mi := &file_RoomMessage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPlayerEnter.ProtoReflect.Descriptor instead.
func (*MsgPlayerEnter) Descriptor() ([]byte, []int) {
	return file_RoomMessage_proto_rawDescGZIP(), []int{1}
}

func (x *MsgPlayerEnter) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MsgPlayerEnter) GetPositionX() float32 {
	if x != nil {
		return x.PositionX
	}
	return 0
}

func (x *MsgPlayerEnter) GetPositionY() float32 {
	if x != nil {
		return x.PositionY
	}
	return 0
}

func (x *MsgPlayerEnter) GetPositionZ() float32 {
	if x != nil {
		return x.PositionZ
	}
	return 0
}

func (x *MsgPlayerEnter) GetForwardX() float32 {
	if x != nil {
		return x.ForwardX
	}
	return 0
}

func (x *MsgPlayerEnter) GetForwardY() float32 {
	if x != nil {
		return x.ForwardY
	}
	return 0
}

func (x *MsgPlayerEnter) GetForwardZ() float32 {
	if x != nil {
		return x.ForwardZ
	}
	return 0
}

func (x *MsgPlayerEnter) GetCurHealth() float32 {
	if x != nil {
		return x.CurHealth
	}
	return 0
}

func (x *MsgPlayerEnter) GetMaxHealth() float32 {
	if x != nil {
		return x.MaxHealth
	}
	return 0
}

type MsgPlayerMove struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DirectionX float32 `protobuf:"fixed32,2,opt,name=directionX,proto3" json:"directionX,omitempty"`
	DirectionY float32 `protobuf:"fixed32,3,opt,name=directionY,proto3" json:"directionY,omitempty"`
	PositionX  float32 `protobuf:"fixed32,4,opt,name=positionX,proto3" json:"positionX,omitempty"`
	PositionY  float32 `protobuf:"fixed32,5,opt,name=positionY,proto3" json:"positionY,omitempty"`
	PositionZ  float32 `protobuf:"fixed32,6,opt,name=positionZ,proto3" json:"positionZ,omitempty"`
}

func (x *MsgPlayerMove) Reset() {
	*x = MsgPlayerMove{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RoomMessage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPlayerMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPlayerMove) ProtoMessage() {}

func (x *MsgPlayerMove) ProtoReflect() protoreflect.Message {
	mi := &file_RoomMessage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPlayerMove.ProtoReflect.Descriptor instead.
func (*MsgPlayerMove) Descriptor() ([]byte, []int) {
	return file_RoomMessage_proto_rawDescGZIP(), []int{2}
}

func (x *MsgPlayerMove) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MsgPlayerMove) GetDirectionX() float32 {
	if x != nil {
		return x.DirectionX
	}
	return 0
}

func (x *MsgPlayerMove) GetDirectionY() float32 {
	if x != nil {
		return x.DirectionY
	}
	return 0
}

func (x *MsgPlayerMove) GetPositionX() float32 {
	if x != nil {
		return x.PositionX
	}
	return 0
}

func (x *MsgPlayerMove) GetPositionY() float32 {
	if x != nil {
		return x.PositionY
	}
	return 0
}

func (x *MsgPlayerMove) GetPositionZ() float32 {
	if x != nil {
		return x.PositionZ
	}
	return 0
}

type MsgPlayerRotate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ForwardX float32 `protobuf:"fixed32,2,opt,name=forwardX,proto3" json:"forwardX,omitempty"`
	ForwardY float32 `protobuf:"fixed32,3,opt,name=forwardY,proto3" json:"forwardY,omitempty"`
	ForwardZ float32 `protobuf:"fixed32,4,opt,name=forwardZ,proto3" json:"forwardZ,omitempty"`
}

func (x *MsgPlayerRotate) Reset() {
	*x = MsgPlayerRotate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RoomMessage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPlayerRotate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPlayerRotate) ProtoMessage() {}

func (x *MsgPlayerRotate) ProtoReflect() protoreflect.Message {
	mi := &file_RoomMessage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPlayerRotate.ProtoReflect.Descriptor instead.
func (*MsgPlayerRotate) Descriptor() ([]byte, []int) {
	return file_RoomMessage_proto_rawDescGZIP(), []int{3}
}

func (x *MsgPlayerRotate) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MsgPlayerRotate) GetForwardX() float32 {
	if x != nil {
		return x.ForwardX
	}
	return 0
}

func (x *MsgPlayerRotate) GetForwardY() float32 {
	if x != nil {
		return x.ForwardY
	}
	return 0
}

func (x *MsgPlayerRotate) GetForwardZ() float32 {
	if x != nil {
		return x.ForwardZ
	}
	return 0
}

type MsgPlayerStop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MsgPlayerStop) Reset() {
	*x = MsgPlayerStop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RoomMessage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPlayerStop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPlayerStop) ProtoMessage() {}

func (x *MsgPlayerStop) ProtoReflect() protoreflect.Message {
	mi := &file_RoomMessage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPlayerStop.ProtoReflect.Descriptor instead.
func (*MsgPlayerStop) Descriptor() ([]byte, []int) {
	return file_RoomMessage_proto_rawDescGZIP(), []int{4}
}

func (x *MsgPlayerStop) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type MsgPlayerShoot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PositionX float32 `protobuf:"fixed32,2,opt,name=positionX,proto3" json:"positionX,omitempty"`
	PositionY float32 `protobuf:"fixed32,3,opt,name=positionY,proto3" json:"positionY,omitempty"`
	PositionZ float32 `protobuf:"fixed32,4,opt,name=positionZ,proto3" json:"positionZ,omitempty"`
	ForwardX  float32 `protobuf:"fixed32,5,opt,name=forwardX,proto3" json:"forwardX,omitempty"`
	ForwardY  float32 `protobuf:"fixed32,6,opt,name=forwardY,proto3" json:"forwardY,omitempty"`
	ForwardZ  float32 `protobuf:"fixed32,7,opt,name=forwardZ,proto3" json:"forwardZ,omitempty"`
}

func (x *MsgPlayerShoot) Reset() {
	*x = MsgPlayerShoot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RoomMessage_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPlayerShoot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPlayerShoot) ProtoMessage() {}

func (x *MsgPlayerShoot) ProtoReflect() protoreflect.Message {
	mi := &file_RoomMessage_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPlayerShoot.ProtoReflect.Descriptor instead.
func (*MsgPlayerShoot) Descriptor() ([]byte, []int) {
	return file_RoomMessage_proto_rawDescGZIP(), []int{5}
}

func (x *MsgPlayerShoot) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MsgPlayerShoot) GetPositionX() float32 {
	if x != nil {
		return x.PositionX
	}
	return 0
}

func (x *MsgPlayerShoot) GetPositionY() float32 {
	if x != nil {
		return x.PositionY
	}
	return 0
}

func (x *MsgPlayerShoot) GetPositionZ() float32 {
	if x != nil {
		return x.PositionZ
	}
	return 0
}

func (x *MsgPlayerShoot) GetForwardX() float32 {
	if x != nil {
		return x.ForwardX
	}
	return 0
}

func (x *MsgPlayerShoot) GetForwardY() float32 {
	if x != nil {
		return x.ForwardY
	}
	return 0
}

func (x *MsgPlayerShoot) GetForwardZ() float32 {
	if x != nil {
		return x.ForwardZ
	}
	return 0
}

type MsgPlayerSetHealth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CurHealth float32 `protobuf:"fixed32,2,opt,name=curHealth,proto3" json:"curHealth,omitempty"`
	MaxHealth float32 `protobuf:"fixed32,3,opt,name=maxHealth,proto3" json:"maxHealth,omitempty"`
}

func (x *MsgPlayerSetHealth) Reset() {
	*x = MsgPlayerSetHealth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RoomMessage_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPlayerSetHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPlayerSetHealth) ProtoMessage() {}

func (x *MsgPlayerSetHealth) ProtoReflect() protoreflect.Message {
	mi := &file_RoomMessage_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPlayerSetHealth.ProtoReflect.Descriptor instead.
func (*MsgPlayerSetHealth) Descriptor() ([]byte, []int) {
	return file_RoomMessage_proto_rawDescGZIP(), []int{6}
}

func (x *MsgPlayerSetHealth) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MsgPlayerSetHealth) GetCurHealth() float32 {
	if x != nil {
		return x.CurHealth
	}
	return 0
}

func (x *MsgPlayerSetHealth) GetMaxHealth() float32 {
	if x != nil {
		return x.MaxHealth
	}
	return 0
}

type MsgPlayerExit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MsgPlayerExit) Reset() {
	*x = MsgPlayerExit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RoomMessage_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPlayerExit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPlayerExit) ProtoMessage() {}

func (x *MsgPlayerExit) ProtoReflect() protoreflect.Message {
	mi := &file_RoomMessage_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPlayerExit.ProtoReflect.Descriptor instead.
func (*MsgPlayerExit) Descriptor() ([]byte, []int) {
	return file_RoomMessage_proto_rawDescGZIP(), []int{7}
}

func (x *MsgPlayerExit) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type MsgPlayerDeath struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	KillerID int32 `protobuf:"varint,2,opt,name=killerID,proto3" json:"killerID,omitempty"`
}

func (x *MsgPlayerDeath) Reset() {
	*x = MsgPlayerDeath{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RoomMessage_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPlayerDeath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPlayerDeath) ProtoMessage() {}

func (x *MsgPlayerDeath) ProtoReflect() protoreflect.Message {
	mi := &file_RoomMessage_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPlayerDeath.ProtoReflect.Descriptor instead.
func (*MsgPlayerDeath) Descriptor() ([]byte, []int) {
	return file_RoomMessage_proto_rawDescGZIP(), []int{8}
}

func (x *MsgPlayerDeath) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MsgPlayerDeath) GetKillerID() int32 {
	if x != nil {
		return x.KillerID
	}
	return 0
}

var File_RoomMessage_proto protoreflect.FileDescriptor

var file_RoomMessage_proto_rawDesc = []byte{
	0x0a, 0x11, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x45, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x2a, 0x0a, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x22,
	0x8a, 0x02, 0x0a, 0x0e, 0x4d, 0x73, 0x67, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x45, 0x6e, 0x74,
	0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x58, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x58,
	0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x59, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x59, 0x12, 0x1c,
	0x0a, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5a, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5a, 0x12, 0x1a, 0x0a, 0x08,
	0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x58, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08,
	0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x58, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x6f, 0x72, 0x77,
	0x61, 0x72, 0x64, 0x59, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x66, 0x6f, 0x72, 0x77,
	0x61, 0x72, 0x64, 0x59, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x5a,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x5a,
	0x12, 0x1c, 0x0a, 0x09, 0x63, 0x75, 0x72, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x09, 0x63, 0x75, 0x72, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x12, 0x1c,
	0x0a, 0x09, 0x6d, 0x61, 0x78, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x09, 0x6d, 0x61, 0x78, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x22, 0xb9, 0x01, 0x0a,
	0x0d, 0x4d, 0x73, 0x67, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x58, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x0a, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x58, 0x12, 0x1e,
	0x0a, 0x0a, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x59, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x0a, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x59, 0x12, 0x1c,
	0x0a, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x58, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x58, 0x12, 0x1c, 0x0a, 0x09,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x59, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x59, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5a, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5a, 0x22, 0x75, 0x0a, 0x0f, 0x4d, 0x73, 0x67, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x66,
	0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x58, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x66,
	0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x58, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x6f, 0x72, 0x77, 0x61,
	0x72, 0x64, 0x59, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x66, 0x6f, 0x72, 0x77, 0x61,
	0x72, 0x64, 0x59, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x5a, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x5a, 0x22,
	0x1f, 0x0a, 0x0d, 0x4d, 0x73, 0x67, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x74, 0x6f, 0x70,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x22, 0xce, 0x01, 0x0a, 0x0e, 0x4d, 0x73, 0x67, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x68,
	0x6f, 0x6f, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x58,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x58, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x59, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x59, 0x12,
	0x1c, 0x0a, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5a, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5a, 0x12, 0x1a, 0x0a,
	0x08, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x58, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x08, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x58, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x6f, 0x72,
	0x77, 0x61, 0x72, 0x64, 0x59, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x66, 0x6f, 0x72,
	0x77, 0x61, 0x72, 0x64, 0x59, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64,
	0x5a, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64,
	0x5a, 0x22, 0x60, 0x0a, 0x12, 0x4d, 0x73, 0x67, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x65,
	0x74, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x75, 0x72, 0x48, 0x65,
	0x61, 0x6c, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x63, 0x75, 0x72, 0x48,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61, 0x78, 0x48, 0x65, 0x61, 0x6c,
	0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x6d, 0x61, 0x78, 0x48, 0x65, 0x61,
	0x6c, 0x74, 0x68, 0x22, 0x1f, 0x0a, 0x0d, 0x4d, 0x73, 0x67, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x45, 0x78, 0x69, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x3c, 0x0a, 0x0e, 0x4d, 0x73, 0x67, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x44, 0x65, 0x61, 0x74, 0x68, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6b, 0x69, 0x6c, 0x6c, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6b, 0x69, 0x6c, 0x6c, 0x65, 0x72,
	0x49, 0x44, 0x2a, 0x97, 0x01, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x65,
	0x72, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4d, 0x6f, 0x76,
	0x65, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x6f, 0x74,
	0x61, 0x74, 0x65, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53,
	0x74, 0x6f, 0x70, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53,
	0x68, 0x6f, 0x6f, 0x74, 0x10, 0x04, 0x12, 0x13, 0x0a, 0x0f, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x53, 0x65, 0x74, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x10, 0x05, 0x12, 0x0e, 0x0a, 0x0a, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x45, 0x78, 0x69, 0x74, 0x10, 0x06, 0x12, 0x0f, 0x0a, 0x0b, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x65, 0x61, 0x74, 0x68, 0x10, 0x07, 0x42, 0x04, 0x5a, 0x02,
	0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_RoomMessage_proto_rawDescOnce sync.Once
	file_RoomMessage_proto_rawDescData = file_RoomMessage_proto_rawDesc
)

func file_RoomMessage_proto_rawDescGZIP() []byte {
	file_RoomMessage_proto_rawDescOnce.Do(func() {
		file_RoomMessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_RoomMessage_proto_rawDescData)
	})
	return file_RoomMessage_proto_rawDescData
}

var file_RoomMessage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_RoomMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_RoomMessage_proto_goTypes = []interface{}{
	(MessageType)(0),           // 0: msg.MessageType
	(*MsgType)(nil),            // 1: msg.MsgType
	(*MsgPlayerEnter)(nil),     // 2: msg.MsgPlayerEnter
	(*MsgPlayerMove)(nil),      // 3: msg.MsgPlayerMove
	(*MsgPlayerRotate)(nil),    // 4: msg.MsgPlayerRotate
	(*MsgPlayerStop)(nil),      // 5: msg.MsgPlayerStop
	(*MsgPlayerShoot)(nil),     // 6: msg.MsgPlayerShoot
	(*MsgPlayerSetHealth)(nil), // 7: msg.MsgPlayerSetHealth
	(*MsgPlayerExit)(nil),      // 8: msg.MsgPlayerExit
	(*MsgPlayerDeath)(nil),     // 9: msg.MsgPlayerDeath
}
var file_RoomMessage_proto_depIdxs = []int32{
	0, // 0: msg.MsgType.msgType:type_name -> msg.MessageType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_RoomMessage_proto_init() }
func file_RoomMessage_proto_init() {
	if File_RoomMessage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_RoomMessage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RoomMessage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPlayerEnter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RoomMessage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPlayerMove); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RoomMessage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPlayerRotate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RoomMessage_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPlayerStop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RoomMessage_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPlayerShoot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RoomMessage_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPlayerSetHealth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RoomMessage_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPlayerExit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RoomMessage_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPlayerDeath); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_RoomMessage_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_RoomMessage_proto_goTypes,
		DependencyIndexes: file_RoomMessage_proto_depIdxs,
		EnumInfos:         file_RoomMessage_proto_enumTypes,
		MessageInfos:      file_RoomMessage_proto_msgTypes,
	}.Build()
	File_RoomMessage_proto = out.File
	file_RoomMessage_proto_rawDesc = nil
	file_RoomMessage_proto_goTypes = nil
	file_RoomMessage_proto_depIdxs = nil
}
